### PR TITLE
Use `[CallerArgumentExpression]` to simplify calling patterns into `Requires` class

### LINKED ISSUE #127: Support CallerArgumentExpression in assertions
Methods on `Requires` (and possibly other classes such as `Assumes` etc.) may benefit from `CallerArgumentExpressionAttribute`.

https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-10#callerargumentexpression-attribute-diagnostics

```c#
// before
Requires.NotNull(name, nameof(name));

// after
Requires.NotNull(name);

### PR DESCRIPTION
**Pull request by AArnott**
Closes #127

### CODE REVIEW

**Comment by RyanToth3** [comment]
Very cool, big fan of this change!

**Review by RyanToth3 — APPROVED** [review]

**Comment by MichaelPeter** [comment]
Love it

**Comment by jdrobison** [comment]
Late to the party here, but +1 on the "love it" comments!

Question:  this works even when targeting .NET Framework, correct?

**Comment by AArnott** [comment]
Correct. The only requirement is that you have a VS 2022 era C# compiler.

**Comment by drewnoakes** [comment]
Amazing, thank you for changing this!

For anyone now facing a mass migration, the following RegEx might be helpful. In VS's _Replace in files_:

- `Requires\.NotNull\((\w+), nameof\(\1\)\);`
- `Requires.NotNull($1);`

image

**Pull request merged**
